### ISSUE TITLE
Subaquatic-v1.0.0-mc1.12.2.jar Crash by Start of Minecraft

### ISSUE THREAD

**Issue by Titoo8899** [jbredwards/Subaquatic#1]
Hi,
your mod crash by the Start of Minecraft. Her the Crash Report:

Crash Report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AssetMover (assetmover-2.1.jar)
  Subaquatic Plugin (Subaquatic-v1.0.0-mc1.12.2.jar)
  Fluidlogged API Plugin (Fluidlogged-API-v1.9.0.6-mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 2/13/23 6:55 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Subaquatic (subaquatic)
Caused by: java.lang.NullPointerException
	at com.cleanroommc.assetmover.AssetMoverHelper.getVersionJson(AssetMoverHelper.java:138)
	at com.cleanroommc.assetmover.AssetMoverHelper.fromMinecraftVersion(AssetMoverHelper.java:74)
	at com.cleanroommc.assetmover.AssetMoverAPI.fromMinecraft(AssetMoverAPI.java:29)
	at git.jbredwards.subaquatic.mod.Subaquatic.constructClient(Subaquatic.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1265072720 bytes (1206 MB) / 2147483648 bytes (2048 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version      | Source                                | Signature                                |
	|:----- |:--------------- |:------------ |:------------------------------------- |:---------------------------------------- |
	| LC    | minecraft       | 1.12.2       | minecraft.jar                         | None                                     |
	| LC    | mcp             | 9.42         | minecraft.jar                         | None                                     |
	| LC    | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge           | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | assetmover      | 2.1          | minecraft.jar                         | None                                     |
	| LC    | fluidlogged_api | 1.9.0.6      | Fluidlogged-API-v1.9.0.6-mc1.12.2.jar | None                                     |
	| LE    | subaquatic      | 1.0.0        | Subaquatic-v1.0.0-mc1.12.2.jar        | None                                     |

	Loaded coremods (and transformers): 
AssetMover (assetmover-2.1.jar)
  
Subaquatic Plugin (Subaquatic-v1.0.0-mc1.12.2.jar)
  git.jbredwards.subaquatic.mod.asm.ASMHandler$Transformer
Fluidlogged API Plugin (Fluidlogged-API-v1.9.0.6-mc1.12.2.jar)
  git.jbredwards.fluidlogged_api.mod.asm.ASMHandler$Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 528.49' Renderer: 'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'

**Comment by Turkey9002** [comment]
I've also experienced a crash when I try to run it with Xaero's World Map but it's been working fine without it.

**Comment by jbredwards** [comment]
@Titoo8899 try with AssetMover v1.1, someone else was having this same problem and downgrading that mod fixed it

**Comment by jbredwards** [comment]
> I've also experienced a crash when I try to run it with Xaero's World Map but it's been working fine without it.

@Turkey9002 fixed in v1.0.1

**Comment by Romz24** [comment]
> fixed in v1.0.1

The problem persists, still can't launch the game

https://mclo.gs/RM482BV

**Comment by jbredwards** [comment]
> The problem persists, still can't launch the game

@Romz24 I was referring to the crash with Xaero's World Map mod. As for the original issue, try doing what I suggested to Titoo and downgrade AssetMover to v1.1

**Comment by Titoo8899** [comment]
> @Titoo8899 try with AssetMover v1.1, someone else was having this same problem and downgrading that mod fixed it

hi,, I have test and the v1.1 have work and the game crash not. Thank you.

**Comment by jbredwards** [comment]
AssetMover added a fix in v2.2
