### ISSUE TITLE
RTG support

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Subaquatic#19]
Title. Allow this mod's biomes to generate in an RTG world.

https://www.curseforge.com/minecraft/mc-mods/realistic-terrain-generation

**Comment by xemnes** [comment]
thought id add to this, having subaquatic installed alongside RTG and geographicraft prevents any modded biomes from spawning for RTG, only vanilla biomes spawn. it might be worth getting in contact with the person maintaining the RTGU fork. https://legacy.curseforge.com/minecraft/mc-mods/realistic-terrain-generation-unofficial

though this may very well be an issue with geographicraft too in terms of the bop biomes not working. but i can only assume the rtg biomes need creating for subaquatic

**Comment by MagmaSlime123** [comment]
> thought id add to this, having subaquatic installed alongside RTG and geographicraft prevents any modded biomes from spawning for RTG, only vanilla biomes spawn. it might be worth getting in contact with the person maintaining the RTGU fork https://legacy.curseforge.com/minecraft/mc-mods/realistic-terrain-generation-unofficial

That mod hasn't been updated since Feb.

**Comment by xemnes** [comment]
that doesnt necessarily mean development has permanently ceased. pull requests can be made too.
the developer is still active in cleanroom, it could be that possibly, hes taken a break.

**Comment by juraj-hrivnak** [comment]
Fixed in RTGU v1.1.0

**Comment by xemnes** [comment]
> Fixed in RTGU v1.1.0

awesome! though as i suspected, bop biomes still dont spawn, which im guessing means is a problem with geographicraft, which i guess would mean that may need forking too?

edit: gonna make a new issue for this

**Comment by MagmaSlime123** [comment]
> > Fixed in RTGU v1.1.0
> 
> awesome! though as i suspected, bop biomes still dont spawn, which im guessing means is a problem with geographicraft, which i guess would mean that may need forking too?
> 
> edit: gonna make a new issue for this

Most of Team RTG's stuff is dead. Though, RTG shouldn't rely on GeographiCraft or BoiomeTweaker to add modded biomes. Subaquatic's a good example of this.
